### ISSUE TITLE
docker部署的时候 sh wolf-demo-init.sh  报错

### ISSUE THREAD

**Issue by muluofeng** [iGeeky/wolf#1]
1) "before all" hook in "{root}"

  0 passing (2m)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 100000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

**Comment by jie123108** [comment]
你可以检查下docker容器是否启动正常.
```
docker ps -a |grep wolf
```
应该有4个容器, wolf-database, wolf-server, wolf-agent-or, wolf-agent-demo 并且确认其都是开启状态.

如果容器启动正常, 你可以尝试, 修改一下`wolf-demo-init.sh`中的超时时间 `--timeout 10000`, 修改成`50000`.

**Comment by iGeeky** [comment]
你可以检查下docker容器是否启动正常.
```
docker ps -a |grep wolf
```
应该有4个容器, wolf-database, wolf-server, wolf-agent-or, wolf-agent-demo 并且确认其都是开启状态.

如果容器启动正常, 你可以尝试, 修改一下`wolf-demo-init.sh`中的超时时间 `--timeout 10000`, 修改成`50000`.

**Comment by muluofeng** [comment]
4个容器都是正常启动的，修改了时间为50000，还是会超时

**Comment by muluofeng** [comment]
[https://note.youdao.com/yws/public/resource/1d675de19d80a20f1d5e40438502197a/xmlnote/WEBRESOURCE94872f9286f10a856526d27c7dc9ef61/15045](url)

**Comment by muluofeng** [comment]
```bash
[root@VM_0_8_centos quick-start-with-docker]# docker ps -a |grep wolf
2cd92fe12a44        igeeky/wolf-agent                          "sh ./entrypoint.sh"     16 minutes ago      Up 16 minutes               10082/tcp, 0.0.0.0:10084->10084/tcp   wolf-agent-demo
afbbcd5662ed        igeeky/wolf-agent                          "sh ./entrypoint.sh"     16 minutes ago      Up 16 minutes               0.0.0.0:10082->10082/tcp              wolf-agent-or
1b27068244eb        igeeky/wolf-server                         "sh ./entrypoint.sh Β   16 minutes ago      Up 16 minutes               0.0.0.0:10080->10080/tcp              wolf-server
813398f4f8a8        postgres:10.7                              "docker-entrypoint.sΒ   16 minutes ago      Up 16 minutes               5432/tcp                              wolf-database
[root@VM_0_8_centos quick-start-with-docker]# 
[root@VM_0_8_centos quick-start-with-docker]# sh wolf-demo-init.sh   


  1) "before all" hook in "{root}"

  0 passing (50s)
  1 failing

  1) "before all" hook in "{root}":
     Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)
```

**Comment by iGeeky** [comment]
请把wolf-database与wolf-server 这两个容器先后重启一下. 然后再试一下吧. 同时使用docker命令查看一下wolf-server这个容器的日志.
