### ISSUE TITLE
 About the return status code of DataNotFoundError and DataExistError

### ISSUE THREAD

**Issue by Hcreak** [iGeeky/wolf#10]
https://github.com/iGeeky/wolf/blob/bc497b0b4624625554a5016c535f7680d07c2735/server/src/middlewares/error-catch.js#L31-L36

I think the return status code here should be 400. What do you think?

If you think so too, I will Fix it in the PR #9

**Comment by iGeeky** [comment]
Yes, it is better to return 400 here. Then you can fix it in PR #9.
