### ISSUE TITLE
采用docker-compose部署，运行wolf-demo-init.sh出错

### ISSUE THREAD

**Issue by Wenhao-Xu** [iGeeky/wolf#13]
组件已经启动成功，但是shell文件运行出现错误
![image](https://user-images.githubusercontent.com/34877512/107143501-5fd54c80-6970-11eb-94f2-72c1db594ee7.png)
![image](https://user-images.githubusercontent.com/34877512/107143507-69f74b00-6970-11eb-825f-fd81a5cd6f93.png)

**Comment by Wenhao-Xu** [comment]
docker版本：1.13.1

**Comment by iGeeky** [comment]
提示信息是, docker容器正在重启, 你看下日志,看看是什么原因导致容器在重启.
