### ISSUE TITLE
docker-compose fast-start instance, can't change password in client by default?

### ISSUE THREAD

**Issue by ak476565** [iGeeky/wolf#14]
![搜狗截图21年02月08日1212_3](https://user-images.githubusercontent.com/3871722/107175106-f05e6c00-6a06-11eb-97eb-a3de0e0ba268.png)

所有权限都开了

**Comment by iGeeky** [comment]
docker-compose.yaml is configured to not allow password changes by default, see here: 
[https://github.com/iGeeky/wolf/blob/master/quick-start-with-docker/docker-compose.yaml#L26](https://github.com/iGeeky/wolf/blob/master/quick-start-with-docker/docker-compose.yaml#L26)
If you need to change the password, please change the CLIENT_CHANGE_PWD value to yes. 
Then docker-compose down, and restart the instance.

**Comment by ak476565** [comment]
its work, tks
