### ISSUE TITLE
application use

### ISSUE THREAD

**Issue by nanoponge** [iGeeky/wolf#16]
I want to know if I want to use this system for my http applications, what should I do?  And if I add a new application in the console, how can I access it?

**Comment by iGeeky** [comment]
1. First of all, Wolf RBAC requires an Agent for permission control. This Agent is usually Nginx (with the ngx_lua plugin), and it is recommended to use openresty directly.
2. You need to configure the reverse proxy of your HTTP application in nginx/openresty. 
3. In the reverse proxy configuration, you need to do the wolf related settings. Here you will use the application information added in Wolf Console, and the corresponding RBAC configuration.

Please refer [https://github.com/iGeeky/wolf/blob/master/docs/deploy.md#5configuring-agent](https://github.com/iGeeky/wolf/blob/master/docs/deploy.md#5configuring-agent)
