### ISSUE TITLE
做的真好，能把小程序认证也加进来不

### ISSUE THREAD

**Issue by daimon99** [iGeeky/wolf#17]

**Comment by iGeeky** [comment]
小程序怎么认证?  跟微信认证有什么区别?

**Comment by daimon99** [comment]
应该差不多。我看了下，咱们这个wolf不支持opened  connect吧？感觉只能做授权，做不了认证。没想明白如果我要用这个做单点认证的话，假设微信（小程序）认证我单写一个应用来做，两边怎么集成起来，用户怎么在小程序里面，调用wx.login之后，怎么给用户发一个wolf的认证令牌。

**Comment by iGeeky** [comment]
wolf实现了OAuth2的接口, 但是这个OAuth2的目的, 是其它web应用, 使用wolf的用户系统及认证(登陆)功能. 
你所说的, 使用小程序的认证, 目前是支持不了的. 
使用小程序/微信(或者github)这样的OAuth认证, 是把 他们当成wolf的用户源, 就是不需要在wolf中添加用户.

所以他们的意义是不一样的.  像wolf这样的系统, 使用微信或者小程序登录, 意义不是很大.  使用LDAP可能更有实际价值一些.

**Comment by daimon99** [comment]
这是个问题。但wolf如果只做授权，那用户数据从哪里来？因为wolf已经是一个应用而非lib了。如果wolf集中管理用户数据，作为一个用户认证中心来讲，是不是具备扩展微信认证，qq认证等各种第三方认证的能力更好？像我是因为apisix了解到wolf，看到把用户中心的界面实现的比较完整，而感兴趣。我是最开始是想把小程序认证集中起来，别每个小程序做一套了。不知道wolf定位是怎么走，怎么考虑哈

**Comment by iGeeky** [comment]
wolf主要功能是基于RBAC的权限管理. 所以通常是应用于B端应用. B端应用我个人感觉,是不适合使用QQ,微信这些来认证的. 像我上面说的, 它如果要支持第三方认证源, 应该是像LDAP, 企业微信,钉钉这种跟业务密切相关的系统. 
wolf不太适合C端的系统, 比如APP的用户管理及认证. C端的需求多变多样, 不太好实现一个通用的系统.
