### ISSUE TITLE
有的api 中将delete的参数放在了body里,虽然http报文没有明确规定,但是好多client不支持

### ISSUE THREAD

**Issue by caobingsheng** [iGeeky/wolf#20]
* 删除用户的api是这样的
* [args-util](https://github.com/iGeeky/wolf/blob/718ada1dd3af2f612b63f86fee39d4fab6444fa5/server/src/util/args-util.js#L56-L62)也是特殊处理的,还加了注释,这个有什么特殊意图吗?我看default分支注释里是有delete的

**Comment by iGeeky** [comment]
在DELETE方法使用 request body参数, 确实rfc里面没说行,也没说不行. 我倾向于可以支持通过body参数,进行DELETE操作.
wolf的客户端通常应该也是服务器, 服务器端的语言, 应该大部分都支持DELETE方法的body参数吧?

**Comment by caobingsheng** [comment]
好的 谢谢
