### ISSUE TITLE
希望能够支持mysql

### ISSUE THREAD

**Issue by u3breeze** [iGeeky/wolf#22]
打算和现有使用mysql的权限系统整合起来使用，不想再单独部署PostgreSQL了。是否能够支持一下？

**Comment by iGeeky** [comment]
@u3breeze 你好, 支持Mysql, 主要麻烦的地方在于应用中大量使用数组这种数据结构.我会调研一下, 看能不能找到一个优雅的方式适配一下Mysql.

**Comment by iGeeky** [comment]
@u3breeze 目前已经支持了MySQL数据库. 这里是部署使用MySQL的方式[https://github.com/iGeeky/wolf/blob/master/docs/deploy-cn.md#mysql](https://github.com/iGeeky/wolf/blob/master/docs/deploy-cn.md#mysql)
