### ISSUE TITLE
这个脚本是在哪里，怎么执行

### ISSUE THREAD

**Issue by zhangbing17** [iGeeky/wolf#25]
![image](https://user-images.githubusercontent.com/23377580/128312972-ffc49ef2-e870-4ce4-9275-0fdc6b381f72.png)

**Comment by edisonwd** [comment]
https://github.com/iGeeky/wolf/blob/master/server/script/db.sql
在 postgreSQL 中执行

**Comment by zhangbing17** [comment]
另外执行server的打包报这个
![image](https://user-images.githubusercontent.com/23377580/128442900-da903ff8-2a31-49af-aed2-b2305653bb1f.png)

执行控制台的打包
![image](https://user-images.githubusercontent.com/23377580/128443005-1d851480-20b3-43c8-9cac-5049e58e1a09.png)
