### ISSUE TITLE
wolf部署访问不了

### ISSUE THREAD

**Issue by zhangbing17** [iGeeky/wolf#26]
npm run dev 后

![image](https://user-images.githubusercontent.com/23377580/128444489-2f90a3ff-7c32-43bb-9664-dd572cca46bc.png)

访问后登录不了
![image](https://user-images.githubusercontent.com/23377580/128444587-d498a4c1-bde0-4621-a15e-8ea2e3e473c7.png)

**Comment by edisonwd** [comment]
建议使用 docker 部署，可以避免出现这种问题

**Comment by zhangbing17** [comment]
> 建议使用 docker 部署，可以避免出现这种问题

没部署docker环境，这应该还差一步
![image](https://user-images.githubusercontent.com/23377580/128457641-f4ec3b27-4aff-44ba-a873-6ed262ff2c67.png)
只有这一个报错，登录不进去

**Comment by iGeeky** [comment]
@zhangbing17 wolf的server你启动成功了吗? 请试着按 这个文档的方法来部署: https://github.com/iGeeky/wolf/blob/master/docs/deploy-cn.md#b%E6%89%8B%E5%8A%A8%E9%83%A8%E7%BD%B2

**Comment by zhangbing17** [comment]
用了docker部署好了
