### ISSUE TITLE
是否适用于生产

### ISSUE THREAD

**Issue by lltime** [iGeeky/wolf#27]
你好：
最近在调研Apisix，第一次了解到wolf。
我想问一下性能、稳定性等是否适合生产环境？
谢谢，

**Comment by iGeeky** [comment]
@lltime wolf稳定性是没什么问题的. 服务器接口包含完备的单元测试用例: https://github.com/iGeeky/wolf/tree/master/server/test.
代码语句覆盖率达到90%以上.
性能方面满足B端应用应该是没什么问题的. 之前有测试过权限检测模块性能, QPS应该在100以上. 
后面我找时间把这部分结果更新到文档上.

**Comment by iGeeky** [comment]
语句覆盖率为92%. 文档补充在: [https://github.com/iGeeky/wolf/blob/master/docs/unittest-cn.md](https://github.com/iGeeky/wolf/blob/master/docs/unittest-cn.md)
agent接口性能测试QPS为240. 文档补充在: [https://github.com/iGeeky/wolf/blob/master/docs/perf-cn.md](https://github.com/iGeeky/wolf/blob/master/docs/perf-cn.md)
