### ISSUE TITLE
about get token problem

### ISSUE THREAD

**Issue by 1731lin** [iGeeky/wolf#3]
```
[root@localhost example]# curl http://127.0.0.1:9080/apisix/plugin/wolf-rbac/login -i -H "Content-Type: application/json" -d '{"appid": "restful-demo", "username":"root", "password":"wolf-123456"}'
HTTP/1.1 500 Internal Server Error
Date: Sat, 21 Nov 2020 03:43:33 GMT
Content-Type: text/plain
Transfer-Encoding: chunked
Connection: keep-alive
Server: APISIX web server

{"message":"request to wolf-server failed! connection refused"}
```
I followed the github steps and I had this problem,{"message":"request to wolf-server failed! connection refused"}

**Comment by iGeeky** [comment]
In this case, it is usually: 
wolf service did not start successfully.
The wolf service did start, but the apisix plug-in has the wrong address and port, or the network between them is not working.
Please check them in turn.

**Comment by iGeeky** [comment]
@Euthpic wolf服务最早是使用的10080. 但是后来由于chrome访问该端口出现异常. 目前改为使用的端口是12180.
所以,你需要在apisix中配置使用的地址为http://内网IP:12180.
