### ISSUE TITLE
limit 256

### ISSUE THREAD

**Issue by caobingsheng** [iGeeky/wolf#30]
- 我看好多地方限制了查询的数据256条,能不能搜索的时候走服务器查询,这样数据多的时候也能查出来
- 其实这个地方最好是用穿梭树

**Comment by iGeeky** [comment]
你好, 限制256的, 不是搜索. 界面上搜索的地方,都是实时查询服务器的. 而且支持分页.
限制256的, 有的是组件内用于显示的. 还有的是列表展示中需要查询(比如权限)ID与名称对应关系的.
256的限制,在某些情况下,可能是有点少了. 我后面把这个值得调整大一些吧.
至于组件的选择, 如果数据量太多了, 使用穿梭树,确实要易用一些. 
之前使用复选框,主要是考虑到界面的统一性, 看起来更整齐一点.

**Comment by iGeeky** [comment]
组件查询数据限制已经修改为512
