### ISSUE TITLE
restapi

### ISSUE THREAD

**Issue by lxiiao** [iGeeky/wolf#33]
请问通过API添加用户时所需要token是必须的吗? 如果是在没有登录的情况下是否可以提供一个永久期限的token用作在本地调用API时使用

**Comment by iGeeky** [comment]
这个是必须的. 因为登录一下获取token并不复杂, 所以这种超级token的模式用处不大. 相反会有一些副作用. 比如无法根据用户查审计日志.

**Comment by lxiiao** [comment]
嗯
