### ISSUE TITLE
restapi-角色权限

### ISSUE THREAD

**Issue by lxiiao** [iGeeky/wolf#34]
看到现在有的api在修改角色拥有的权限时需要将已有的跟新加的合并后再次传递, 是否考虑增加修改角色拥有的权限可以增量添加权限

**Comment by iGeeky** [comment]
嗯, 这个后面看一下, 可以支持一下.

**Comment by lxiiao** [comment]
嗯, 好的

**Comment by iGeeky** [comment]
@lxiiao  已经添加单独的方法来添加角色的权限, 请看文档:
https://github.com/iGeeky/wolf/blob/master/docs/admin-api-cn.md#%E6%B7%BB%E5%8A%A0%E8%A7%92%E8%89%B2%E6%9D%83%E9%99%90
