### ISSUE TITLE
wolf-console-limit

### ISSUE THREAD

**Issue by lxiiao** [iGeeky/wolf#35]
现有的wolf控制台在下拉选择框时使用limit限制了查询条数, 是否可以将其limit设置大一点,? 避免部分数据被过滤掉

**Comment by iGeeky** [comment]
目前是限制了512的数量. 考虑到下拉框数据太多也不好选择, 所以做了限制. 
你目前的权限或角色数量,已经超过512了吗?

**Comment by lxiiao** [comment]
是的, 并且马上过一千了. 而且这种下拉框在数据量多的情况下操作非常不便, 看看能否考虑后期更换成其他组件

**Comment by iGeeky** [comment]
@lxiiao 最新的0.5.2版本已经支持了穿梭框来选择权限. 权限数量限制也提高到10000了.
