### ISSUE TITLE
资源或者权限能否限制到host？

### ISSUE THREAD

**Issue by alfred-liu96** [iGeeky/wolf#38]
你好，请问wolf的资源能否指定host吗？
我现在使用apisix结合wolf做权限管理，不知道如何分别设置测试与线上api的权限

**Comment by iGeeky** [comment]
不行,目前区分应该是按应用来做的.
如果你需要区分测试环境跟线上环境,最好是部署两套. 
如果希望使用一套,那可以定义不同的应用.

**Comment by alfred-liu96** [comment]
我线上和测试环境只有域名是不同的，如果使用应用来区分，要如何配置呢？

我在wolf上新增了应用，也在apisix上新增了对应appid的consumer，不过我没找到区分环境的设置在哪

**Comment by alfred-liu96** [comment]
> 不行,目前区分应该是按应用来做的. 如果你需要区分测试环境跟线上环境,最好是部署两套. 如果希望使用一套,那可以定义不同的应用.

我线上和测试环境只有域名是不同的，如果使用应用来区分，要如何配置呢？

我在wolf上新增了应用，也在apisix上新增了对应appid的consumer，不过我没找到区分环境的设置在哪

**Comment by iGeeky** [comment]
@alfred-liu96  就是在apisix设置设置不同的appId. 比如正式环境的appId叫 `app`, 测试环境叫 `app_test`.
这样他们就能用同一个wolf,但是有两套配置了.
