### ISSUE TITLE
No api doc for user-role

### ISSUE THREAD

**Issue by tiannian** [iGeeky/wolf#4]
Seems miss some doccument about `/wolf/user-role`. I can't use RESTful api to bind roles or permissions.

**Comment by iGeeky** [comment]
I'm sorry, but the api documentation is really missing this section. 
You can refer to the code in the test case: [https://github.com/iGeeky/wolf/blob/master/server/test/70.user-role.test.js](https://github.com/iGeeky/wolf/blob/master/server/test/70.user-role.test.js)
I'll add the documentation later.

**Comment by tiannian** [comment]
ok. thank you.

**Comment by iGeeky** [comment]
The interface documentation is available here: 
https://github.com/iGeeky/wolf/blob/master/docs/admin-api.md#API-User-Role
