### ISSUE TITLE
user role assignment on wolf dashboard?

### ISSUE THREAD

**Issue by rjiang-ptm** [iGeeky/wolf#43]
Wolf has api to set user-role - assign a role to a given user, but it doesn't seem to support this action on wolf dashboard?

Not sure if I missed anything, but there seems to be no way to query or set the user-role info on wolf dashboard?

**Comment by iGeeky** [comment]
On the User List page, in the `Permissions` column, click `Detail`. This will display the applications to which the user has access. After clicking on the `application`, you can set the permissions and roles.
