### ISSUE TITLE
不启动redis cache的情况下，wolf-cache被指向redis, 登录接口超时

### ISSUE THREAD

**Issue by NJLOVER** [iGeeky/wolf#44]
![image](https://user-images.githubusercontent.com/6790302/184080024-f92363c7-5d04-43a2-b93c-1d36b11a4905.png)

![image](https://user-images.githubusercontent.com/6790302/184080330-1aa126f7-2694-48f6-bd59-6f4ca1e13aea.png)

**Comment by NJLOVER** [comment]
![image](https://user-images.githubusercontent.com/6790302/184080574-647c7d91-10fe-4f91-b196-c7fad8fa7531.png)

**Comment by iGeeky** [comment]
k8s的配置是还有点问题. 我正在处理这个问题.
你可以先用docker-compose方式启动.

**Comment by iGeeky** [comment]
@NJLOVER  已经更新了k8s配置及文档, 请更新仓库, 然后查看文档.
[https://github.com/iGeeky/wolf/blob/master/quick-start-with-docker/README-K8S-CN.md](https://github.com/iGeeky/wolf/blob/master/quick-start-with-docker/README-K8S-CN.md)
