### ISSUE TITLE
管理接口能提供按用户名获取用户信息的功能么？

### ISSUE THREAD

**Issue by laokan** [iGeeky/wolf#45]
/wolf/user/list 
接口是 按key 多个字段like的，
能不能加个参数通过 username 精确匹配userinfo

**Comment by iGeeky** [comment]
https://github.com/iGeeky/wolf/blob/master/docs/admin-api-cn.md#query%E5%8F%82%E6%95%B0-5
已经支持, 请使用username进行查询, 将进行精确匹配.
