### ISSUE TITLE
The dashboard login need  add human vaild ban the bot 

### ISSUE THREAD

**Issue by laokan** [iGeeky/wolf#46]
RT.

**Comment by iGeeky** [comment]
@laokan  The latest commits to the code repository already support Captcha. You need to set the environment variable: export CONSOLE_LOGIN_WITH_CAPTCH=yes to enable this feature

**Comment by laokan** [comment]
great job!

**Comment by laokan** [comment]
i add the CONSOLE_LOGIN_WITH_CAPTCH in the docker compose yaml  but the console login  page not show the captch image. and can login success
