### ISSUE TITLE
问题：是否能只用API权限验证功能，而不用wolf的用户登录功能

### ISSUE THREAD

**Issue by magicgw0928** [iGeeky/wolf#48]
**背景**：公司里已经有现成的OIDC服务用作单点登录，但是没有对资源的权限管控服务，需要自行额外开发菜单权限管理和API权限管理与验证功能。
**需求与规划**：目前已经通过APISIX Gateway的OIDC插件完成了用户登录验证功能，打算在Gateway通过调用wolf的Admin API来验证当前用户是否有权限。（当前拿到的是公司OIDC服务颁发的AccessToken，不是通过wolf登录的token）
**问题**：现有/wolf/rbac/access_check接口中是通过x-rbac-token加上action和resName参数做校验的，但是如上所述，Gateway没有x-rbac-token。是否有可能增加一个不需要x-rbac-token的公共服务接口，然后在request body中传递{userid, appid, action, resName}，然后wolf返回校验是否通过（response只需告知true或false，不需要userinfo）
或者，是否还有其他什么好的集成方案？万分感谢！！！

**Comment by iGeeky** [comment]
这个怕是不行. 控制台进行授权管理也需要用户信息的.
你可以参考wolf中的ldap登录, 实现在wolf中用OIDC进行登录. 这样用户信息就可以同步到wolf系统中.
