### ISSUE TITLE
 Expireation time for administration backend Token

### ISSUE THREAD

**Issue by Hcreak** [iGeeky/wolf#5]
What is the expiration time of the token obtained through the `Console login` interface?  I did not clearly see it in the document, and I found it is really long, So is it permanent? Thanks

**Comment by iGeeky** [comment]
The token returned by Console Login has an expiration time of 30 days by default.
You can change it with the `RBAC_TOKEN_EXPIRE_TIME` environment variable. 
I've added it to the documentation.  [Server configuration items](https://github.com/iGeeky/wolf/blob/master/docs/deploy.md#2server-configuration-items)

**Comment by Hcreak** [comment]
ok. thank you.
