### ISSUE TITLE
How to allow/disallow routes according to role in apisix

### ISSUE THREAD

**Issue by yrimjang** [iGeeky/wolf#50]
I am using apisix and am trying to do rbac with wolf-rbac. When I looked at the consumer and route options in apisix, it seemed like there was no separate setting for the role. When an apisix route is requested with a token received from wolf-rbac, how can the route know its permissions?

**Comment by iGeeky** [comment]
Hello, the roles for users are set in the wolf console. The permissions for a route are added/set in the resources. For a new route, you need to add a resource, which sets the corresponding URL (prefix or suffix) and the required permissions for it. Users then need to be associated with roles, and roles associated with permissions.
