### ISSUE TITLE
登录时能支持验证码验证吗

### ISSUE THREAD

**Issue by qqisee** [iGeeky/wolf#51]
登录场景要求多因素验证，有支持验证码验证的打算吗

**Comment by iGeeky** [comment]
你说的验证码是指Google Authenticator的验证码吗?

**Comment by qqisee** [comment]
![无标题](https://github.com/iGeeky/wolf/assets/25243560/f6cb813a-61a7-469e-8e16-158f28955af8)
就是常见的数字字母验证码

**Comment by iGeeky** [comment]
图形验证码是支持的. 可以通过配置'CONSOLE_LOGIN_WITH_CAPTCHA'打开. 这个支持的管理控制台支持captcha, 不是agent登录的.
请看文档: https://github.com/iGeeky/wolf/blob/master/docs/deploy-cn.md#2%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE%E9%A1%B9

**Comment by qqisee** [comment]
嗯嗯，那请问agent有支持的计划吗

**Comment by iGeeky** [comment]
暂时没有. agent因为是以接口方式对外, 并没有UI界面. 如果要提供验证码,需要与UI紧密的耦合.

**Comment by qqisee** [comment]
好的，谢谢
